import type { NextPage } from "next";
import Head from "next/head";
import { Center } from "../src/layout";
import { WaveElement } from "../src/geometry";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WaveElement
        color1="$pink100"
        color2="$green500"
        height="100vh"
        mt="-100px"
      ></WaveElement>
    </>
  );
};

export default Home;
