import type { NextPage } from "next";
import Head from "next/head";
import { Center } from "@ui";
import { BaseTemplate } from "@templates";

const Home: NextPage = () => {
  return (
    <BaseTemplate>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>test</Center>
    </BaseTemplate>
  );
};

export default Home;
