version: "3"

networks:
  default:
    external:
      name: build

services:
  server:
    hostname: gitea.your.host.local
    container_name: gitea
    image: gitea/gitea:1.16
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
